### ISSUE TITLE
Support "forEach Loop"

### ISSUE THREAD

**Issue by danielbayerlein** [danielbayerlein/language-galen#5]
See http://galenframework.com/docs/reference-galen-spec-language-guide/#forEachLoop

**Comment by t2hv33** [comment]
{
        'comment': 'forEach Loop keyword'
        'match': '^\\s*(@forEach)\\s.+\\s(as)\\s.+\\s'
        'captures':
          '1':
            'name': 'keyword.control.forEach.galen'
          '2':
            'name': 'keyword.control.forEach.galen'
      }
